# Generated by Django 3.2.13 on 2023-10-28 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LwoBajaji', '0004_auto_20231028_2216'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='total_bajaji',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='total_drivers',
        ),
    ]
