# Generated by Django 3.2.13 on 2023-10-30 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LwoBajaji', '0006_receiver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LwoBajaji.receiver'),
        ),
    ]
