# Generated by Django 3.2.13 on 2023-10-30 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LwoBajaji', '0008_remove_unknowndriver_balance_before'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='receiver',
        ),
        migrations.AlterField(
            model_name='receiver',
            name='total_amount_received',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
