# Generated by Django 3.2.13 on 2023-10-31 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LwoBajaji', '0011_receiver_amount_withdrawn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='receiver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='LwoBajaji.receiver'),
        ),
    ]
