# Generated by Django 3.2.13 on 2023-10-31 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LwoBajaji', '0012_alter_payment_receiver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receiver',
            name='phone_number',
            field=models.IntegerField(max_length=15),
        ),
    ]
