# Generated by Django 3.2.13 on 2023-10-31 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LwoBajaji', '0013_alter_receiver_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receiver',
            name='phone_number',
            field=models.CharField(max_length=15),
        ),
    ]
