# Generated by Django 3.2.13 on 2023-10-31 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LwoBajaji', '0014_alter_receiver_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='receiver',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='LwoBajaji.receiver'),
            preserve_default=False,
        ),
    ]
