# Generated by Django 3.2.13 on 2023-10-31 11:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('LwoBajaji', '0016_auto_20231031_1114'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_number', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=200)),
                ('phoneII', models.CharField(max_length=200)),
                ('plate_no', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=255)),
                ('sponsor', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('finish_date', models.DateField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='drivers/')),
            ],
        ),
        migrations.CreateModel(
            name='UnknownDriver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('payment_date', models.DateField()),
                ('transaction_type', models.CharField(max_length=255)),
                ('received_from', models.CharField(max_length=255)),
                ('txn_id', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Receiver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=15)),
                ('total_amount_received', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('amount_withdrawn', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField()),
                ('transaction_type', models.CharField(max_length=255)),
                ('received_from', models.CharField(max_length=255)),
                ('txn_id', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('balance_before', models.FloatField()),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LwoBajaji.driver')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LwoBajaji.receiver')),
            ],
        ),
        migrations.CreateModel(
            name='Bajaji',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_no', models.CharField(max_length=15)),
                ('date_contract', models.DateField()),
                ('status_payment', models.CharField(choices=[('not-paid', 'not-paid'), ('paid-day', 'paid-day'), ('paid-month', 'paid-month')], default='not-paid', max_length=20)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LwoBajaji.driver')),
            ],
        ),
    ]
