# Generated by Django 3.2.13 on 2023-11-03 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LwoBajaji', '0017_bajaji_driver_payment_receiver_unknowndriver'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bajaji',
            name='status_payment',
        ),
        migrations.AddField(
            model_name='driver',
            name='status_payment',
            field=models.CharField(choices=[('not-paid', 'not-paid'), ('paid-day', 'paid-day'), ('paid-month', 'paid-month')], default='not-paid', max_length=20),
        ),
    ]
